# Site settings
author: Natalie Taktachev
title: Flatiron
header-img: img/home-bg.png
email: ntaktach@gmail.com
copyright_name: Natalie Taktachev
description: > # this means to ignore newlines until "baseurl:"
  Online Bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  naturalnat

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
